### ISSUE TITLE
How to enable "Show me suggestions from history..."

### ISSUE THREAD

**Issue by BuiltByLou** [marlock9/edge-debloat#2]
Hi, 

anyone know how to enable the setting:
"Show me suggestions from history, favorites and other data on this device using my typed characters"

![Screenshot 2024-09-04 094727](https://github.com/user-attachments/assets/ed363e36-12ce-4a49-bf57-d4bd352abcd2)

**Comment by marlock9** [comment]
With my registry keys, I don't have this thing permanently disabled. It's not managed and can be turned on.

**Comment by BuiltByLou** [comment]
You right - a debloat app for windows added the keys blocking that option

**Comment by BuiltByLou** [comment]
It appears this issue was caused by a debloating app that created a registry key in `Computer\HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge`. The specific key in question is:

`"ShowSearchSuggestionsGlobal"=dword:00000001`

- To disable search suggestions, set the value to `00000000`.
- To enable search suggestions, set the value to `00000001`.
